# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# ***** 追加インポート5/8 山本
import csv
import datetime

class Ui_MainWindow(object):
    data={'sleep':3,'meal':3,'fit':3,'stress':3,'condition':3,'concentration':3,'trustMe':3,'trustOther':3,'trustFromOther':3}
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 840)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 625, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(410, 625, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_Past = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Past.setGeometry(QtCore.QRect(120, 740, 181, 51))   #配置変更 5/8 山本
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Past.setFont(font)
        self.pushButton_Past.setObjectName("pushButton_Past")
        self.pushButton_Resist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Resist.setGeometry(QtCore.QRect(500, 740, 181, 51)) #配置変更 5/8 山本
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Resist.setFont(font)
        self.pushButton_Resist.setObjectName("pushButton_Resist")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 260, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 350, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 440, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(110, 490, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 540, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 140, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")


        # ***** ラジオボタン設置処理 2024/05/03 寺島
        
        radioBasePosX = 240 # 左端のラジオボタンのx座標
        radioBasePosY = 90 # 最初の項目のラジオボタンのy座標
        dY = 0 # y座標の位置調整用
        
        # 各項目について、5つのラジオボタンをグループ化する
        self.groupNameList = ['sleep', 'meal','fit','stress','condition','concentration','trustMe','trustOther','trustFromOther']
        self.radioGroupDict = {} # 各グループを参照しやすいように、まとめて辞書化する
        # ⇒これにより、self.radioGroups[self.groupNameList[n]] で項目ごとのボタングループを参照できる
        

        # 外側のループ: 各項目についてのループ
        for i in range(9): 
            self.radioGroupDict[self.groupNameList[i]] = QtWidgets.QButtonGroup(MainWindow) # ボタングループの辞書に空のグループを作成
            
            # 内側のループ: 5つのラジオボタンを配置する
            for j in range(5):
                objectName = self.groupNameList[i] + '_' + str(j+1)
                posX = radioBasePosX + (100 * j)
                posY = radioBasePosY + dY
                val = j+1 # j番目のラジオボタンの内部値(id)はj+1
                
                radio = self.makeRadio(objectName, posX, posY) # ラジオボタン作成
                
                if j == 2:
                    radio.setChecked(True) # 初期状態では3にチェックをつけておく
                
                self.radioGroupDict[self.groupNameList[i]].addButton(radio, val) # 作成したラジオボタンをグループに追加
                
            dY += 50 # 次の項目へ移動するため、y座標を下げる
            
            if (i+1)%3 == 0:
                dY += 27 # 3項目ごとに次の大項目へ移動するため、さらにy座標を少し下げる
                

        # ***** ラジオボタン設置ここまで



        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(230, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(330, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(530, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(630, 40, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 220, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 390, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(230, 220, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(330, 220, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(430, 220, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(530, 220, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(630, 220, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(630, 400, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(530, 400, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(330, 400, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(230, 400, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(430, 400, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(219, 10, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "セルフチェック トップ"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "予防・回復対処："))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "備考："))
        self.pushButton_Past.setText(_translate("MainWindow", "過去のデータを見る"))
        self.pushButton_Resist.setText(_translate("MainWindow", "登録"))
        self.label_2.setText(_translate("MainWindow", "セルフチェック"))
        self.label.setText(_translate("MainWindow", "睡眠"))
        self.label_3.setText(_translate("MainWindow", "運動"))
        self.label_4.setText(_translate("MainWindow", "不安・ストレスがない"))
        self.label_5.setText(_translate("MainWindow", "身体の調子"))
        self.label_6.setText(_translate("MainWindow", "集中力"))
        self.label_7.setText(_translate("MainWindow", "自分を信頼"))
        self.label_8.setText(_translate("MainWindow", "他人を信頼"))
        self.label_9.setText(_translate("MainWindow", "他人から信頼"))
        self.label_10.setText(_translate("MainWindow", "食事"))
        self.label_11.setText(_translate("MainWindow", "1"))
        self.label_12.setText(_translate("MainWindow", "3"))
        self.label_13.setText(_translate("MainWindow", "2"))
        self.label_14.setText(_translate("MainWindow", "4"))
        self.label_15.setText(_translate("MainWindow", "5"))
        self.label_16.setText(_translate("MainWindow", "生活基盤"))
        self.label_17.setText(_translate("MainWindow", "心と体のサイン"))
        self.label_18.setText(_translate("MainWindow", "信頼のサイン"))
        self.label_19.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "2"))
        self.label_21.setText(_translate("MainWindow", "3"))
        self.label_22.setText(_translate("MainWindow", "4"))
        self.label_23.setText(_translate("MainWindow", "5"))
        self.label_24.setText(_translate("MainWindow", "5"))
        self.label_25.setText(_translate("MainWindow", "4"))
        self.label_26.setText(_translate("MainWindow", "2"))
        self.label_27.setText(_translate("MainWindow", "1"))
        self.label_28.setText(_translate("MainWindow", "3"))
        self.label_29.setText(_translate("MainWindow", "低い　　　　　　　　　　　　　　　　　　　　　　　  　 高い"))
        self.menu.setTitle(_translate("MainWindow", "セルフチェック"))



    # ***** ラジオボタン関係の関数 2024/05/06 寺島
    
    def makeRadio(self, objectName, pos_x, pos_y):
        size_x = 21
        size_y = 16
        
        radio = QtWidgets.QRadioButton("", self.centralwidget)
        radio.setObjectName(objectName)
        radio.setGeometry(QtCore.QRect(pos_x, pos_y, size_x, size_y))
        
        radio.clicked['bool'].connect(self.radioToggled) # これは最終的に不要かも。↓参照
        
        return radio
    
    
    def radioToggled(self, value):
        """ この関数は最終的に不要かも
        """
        
        # ラジオボタングループを辞書化したことにより、
        # self.radioGroupDict["{項目名}"].checkedId() で
        # 「ある項目について何番目のラジオボタンがチェックされているか」を取得できます。
        
        # たとえば睡眠の3にチェックが入っているとき、self.radioGroupDict["sleep"].checkedId() = 3 です。
        
        # これを利用すれば、csv書き込みの際に項目名でループをかけて
        # 効率的に各項目の値を取得できます。
        
        # つまり、「登録」ボタンを押したときにまとめて値を取得すればよく、
        # 個別の「ラジオボタンがクリックされたとき」の関数は不要になります。
        
        # 以下、「登録」ボタンを押したときの関数実装例。色々省略しています
        # def onPushRegister(self):
        #   for name in self.groupNameList:
        #       val = self.radioGroupDict[name].checkedId()
        #       write_to_csv(val + ',')
        
        pass
    
    # ***** ラジオボタン関連の関数ここまで
    
    
    # ***** 「登録」ボタン押下時処理 5/8 山本
    # *****              編集・追記 5/9 山本
    def pushResistButtonSlot(self):
        with open('test.csv','a',encoding='utf-8') as f:# 現状とりあえずtest.csvで設定してあります。
                            #'a'で追記(append)モード。
            writer = csv.writer(f)
            writer.writerow(datetime.date.today()+',') #タイムスタンプ(date)
        #   ラジオボタンの値を取得ー＞csvに書き込み
        for name in self.groupNameList:
            val = self.radioGroupDict[name].CheckedId()
            writer.writerow(val + ",")
        writer.writerow()
        # ***** 完了の旨のメッセージボックスを表示 5/10 山本
        writer.writerow()
        msg_box = QtWidgets.QMessageBox()
        msg_box.setIcon(msg_box.information)
        msg_box.setText('登録完了')
        msg_box.setInformativeText('本日のセルフチェックの登録が完了しました。')
        msg_box.setStandardButtons(msg_box.Ok)
        # メッセージボックスを表示
        msg_box.exec_()
    # ***** 「登録」ボタン押下時処理 ここまで
    
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
